---
title: "hw2_maps"
output: html_document
date: "2025-11-09"
---


```{r}
rm(list = ls())

LowellLink="https://github.com/DACSS690D-SpatialAnalysis/Homework2/raw/refs/heads/main/lowell_analysis.gpkg"

#create temporary file path on computer
#.gpkg extension for geopackage
temp_file <- tempfile(fileext = ".gpkg")

#download the file from the URL 
download.file(LowellLink, temp_file, mode = "wb")

library(sf)

st_layers(temp_file)    #st_layers shows whats inside the gpkg file 

Lowell <- st_read(temp_file)  
```
```{r}
suitable_roads <- st_read(temp_file, layer = 'suitable_roads')
gas_buffered <- st_read(temp_file, layer = 'gas_buffered')
gas_centers <- st_read(temp_file, layer = 'gas_centers')
fuel_stations <- st_read(temp_file, layer = 'fuel_stations')
schools <- st_read(temp_file, layer = 'schools')
fuel_relocate <- st_read(temp_file, layer = 'fuel_relocate')
```
```{r}
library(ggplot2)
library(ggspatial)
library(sf)

lowell_map <- ggplot() +
  annotation_map_tile(type = "cartolight", zoom = 14, zoomin = 0) +  
  geom_sf(data = suitable_roads, 
          aes(color = 'Suitable Roads'),
          size = 2) +
  geom_sf(data = gas_buffered, 
          aes(color = 'Relocation Zone'), 
          fill = NA, size = 4) +
  geom_sf(data = gas_centers, 
          aes(color = 'Center of Relocation Zone'), 
          shape = 3, size = 4) + 
  geom_sf(data = fuel_stations, 
          aes(color = 'Existing Stations'), 
          size = 3) +
  geom_sf(data = schools, 
          aes(color = 'Schools'), 
          size = 3) +
  geom_sf(data = fuel_relocate, 
          aes(color = 'Stations to Relocate'), 
          size = 3) +
  scale_color_manual(
    name = "Legend",
    values = c('Suitable Roads' = 'orange',
               'Relocation Zone' = 'red',
               'Center of Relocation Zone' = 'red',
               'Existing Stations' = 'black',
               'Schools' = 'green',
               'Stations to Relocate' = 'purple'),
    breaks = c('Suitable Roads', 'Relocation Zone',
               'Center of Relocation Zone', 'Existing Stations',
               'Schools', 'Stations to Relocate')) +
  scale_x_continuous(labels = label_number(scale = 1/100, suffix = " km")) +
  scale_y_continuous(labels = label_number(scale = 1/100, suffix = " km")) +
  labs(x = "Easting", 
       y = "Northing",
       title = "Lowell, MA: Gas Stations and Schools") +
  theme_minimal()

lowell_map

```

```{r}
saveRDS(lowell_map, file = "lowell_map.rds")

```



